### ISSUE TITLE
iOS sendPushTokenToIntercom is not available

### ISSUE THREAD

**Issue by nadavhalfon** [Fiksuruoka-fi/capacitor-intercom#16]
**Describe the bug**
iOS sendPushTokenToIntercom is not available - and the automatic send token doesn't work
It will help to manually push the token in javascript

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eljass** [comment]
Tested and worked with these fixes: https://github.com/Fiksuruoka-fi/capacitor-intercom/pull/14/commits/0dad7b11e9e55fd23b9e8e522c4eb646728756c2

**Comment by eljass** [comment]
Fixed in 4.3.0
