### ISSUE TITLE
Typo in hmac string

### ISSUE THREAD

**Issue by hildorjr** [Fiksuruoka-fi/capacitor-intercom#21]
There is a string that should be "hmac" but is "hmsc" in line 269 of the IntercomPlugin.swift file.

https://github.com/Fiksuruoka-fi/capacitor-intercom/blob/main/ios/Plugin/IntercomPlugin.swift#L269

If there is a way to please fix this quickly would be great. This is the only Intercom Capacitor package getting updated competently.

**Comment by eljass** [comment]
Thanks for noticing @hildorjr! The fix has been released now.
