### ISSUE TITLE
updateUnreadCount notification object is nil

### ISSUE THREAD

**Issue by nadavhalfon** [Fiksuruoka-fi/capacitor-intercom#31]
**Describe the bug**
<img width="616" alt="image" src="https://github.com/Fiksuruoka-fi/capacitor-intercom/assets/32557985/d7616e4a-dc78-4d8d-8f30-0e46fe5d526a">
When using the code above, in xcode debugging 
`guard let unreadCount = notification.object as? Data else {
                    return
                }`
notification.object is always nil

**To Reproduce**
1. Perform the above snippet
2. Send or read Intercom message in ios
3. The notification event listener fires
4. See notification object is nil

**Expected behavior**
Update read count receives number

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro
 - OS: iOS 16.5.1
 - Browser: Capacitor

**Additional context**

**Comment by reslear** [comment]
thx for example )
