### ISSUE TITLE
Problem with building Android app

### ISSUE THREAD

**Issue by ArtBoguslavskiy** [Fiksuruoka-fi/capacitor-intercom#33]
Hello mate.
You have done a great job updating the Intercom plugin.
Thanks a lot for that.

It works great on iOS.

**Describe the bug**
But when I try to build the Android app I get errors.

<img width="1511" alt="Снимок экрана 2024-03-15 в 14 46 13" src="https://github.com/Fiksuruoka-fi/capacitor-intercom/assets/13527064/189c8cdb-a1a6-42d8-998a-a4a69607d68b">

Maybe I'm wrong, but I think the problem is with the `$firebaseMessagingVersion` variable.

Could you please help me with it?

Also just FYI, I checked to build app without the plugin, android app build successfully.

**To Reproduce**
Try to build the Android app

**Comment by eljass** [comment]
@ArtBoguslavskiy sorry for late answer, you can add that one in your project's `./android/variables.gradle` file. We are using currently `firebaseMessagingVersion = '23.1.2'`. Without this one push notifications won't work on Android app from Intercom.

You can refer these to know more about it: https://developers.intercom.com/installing-intercom/android/fcm-push-notifications/ and https://capacitorjs.com/docs/apis/push-notifications#android
